# Generated by Django 2.2 on 2022-04-02 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_reservationlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='available',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='name',
            new_name='hotel_name',
        ),
        migrations.RemoveField(
            model_name='reservationlist',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='reservationlist',
            name='guest_name',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservationlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.ReservationList')),
            ],
        ),
    ]
