# Generated by Django 2.2 on 2022-04-08 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_auto_20220402_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='guest_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_list', to='hotelapp.ReservationList'),
        ),
    ]
